---
version: "3"

services:
  concourse:
    image: concourse/concourse
    command: quickstart
    privileged: true
    expose: ["8080"]
    restart: unless-stopped
    environment:
      - CONCOURSE_POSTGRES_HOST=${POSTGRES_HOST}
      - CONCOURSE_POSTGRES_USER=${POSTGRES_USER}
      - CONCOURSE_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - CONCOURSE_POSTGRES_DATABASE=concourse
      - CONCOURSE_EXTERNAL_URL=https://${DOMAIN}
      - CONCOURSE_ADD_LOCAL_USER=${LOCAL_ADMIN_USER}:${LOCAL_ADMIN_PASSWORD}
      - CONCOURSE_MAIN_TEAM_LOCAL_USER=admin
      - CONCOURSE_MAIN_TEAM_OIDC_GROUP=${OIDC_ADMIN_GROUP}
      - CONCOURSE_GARDEN_DNS_PROXY_ENABLE=true
      - CONCOURSE_WORKER_GARDEN_DNS_PROXY_ENABLE=true
      - CONCOURSE_LIDAR_SCANNER_INTERVAL=3h
      - CONCOURSE_DEFAULT_BUILD_LOGS_TO_RETAIN=50
      - CONCOURSE_DEFAULT_DAYS_TO_RETAIN_BUILD_LOGS=14
      - CONCOURSE_MAX_BUILD_LOGS_TO_RETAIN=100
      - CONCOURSE_MAX_DAYS_TO_RETAIN_BUILD_LOGS=30
      - CONCOURSE_VAULT_URL=https://${VAULT_ADDR}
      - CONCOURSE_VAULT_AUTH_BACKEND=approle
      - CONCOURSE_VAULT_AUTH_PARAM=role_id:${VAULT_ROLE_ID},secret_id:${VAULT_SECRET_ID}
      - CONCOURSE_VAULT_AUTH_BACKEND_MAX_TTL=1h
      - CONCOURSE_OIDC_DISPLAY_NAME=${OIDC_NAME}
      - CONCOURSE_OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - CONCOURSE_OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - CONCOURSE_OIDC_ISSUER=${OIDC_ISSUER}
      - CONCOURSE_OIDC_USER_NAME_KEY=email
      - CONCOURSE_OIDC_GROUPS_KEY=groups
      - CONCOURSE_PROMETHEUS_BIND_IP=0.0.0.0
      - CONCOURSE_PROMETHEUS_BIND_PORT=1992
    networks:
      - default
      - traefik_proxy-external
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agola.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.agola.tls.certresolver=leresolver"
      - "traefik.docker.network=traefik_proxy-external"
      - "traefik.http.services.agola.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.agola.middlewares=sslheader" # adds ssl header in an attempt to help websockets work better
networks:
  traefik_proxy-external:
    external: true
volumes:
  pg-data:
